name = "tpv-app"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[[kv_namespaces]]
binding = "APP_SESSIONS"
id="62812a096852406f858f311e3533b0d4"

[vars]
LIBSQL_DB_URL="libsql://bakery-db-njmaldo.aws-us-west-2.turso.io"
LIBSQL_DB_AUTH_TOKEN="eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjEwOTQxMzgsImlkIjoiNmViZmQyYjUtMThiMy00ZGMyLWJhZTAtYzU5NWMyZGIwMzhkIiwicmlkIjoiNjJmMWNlMDItNmI1NS00NjBjLTlkYmUtNjhlY2Q1NmFkMzI4In0.AC-aAAB04FwWdA99gdyRh-1pnI3ae4SSHdAkwp_b7DTLH3HtjoKP0fAKMKjI3JxNn4ebooZ_jyESK46S9_SZDg"

[observability]
enabled = true
